-- Oracle Database 23ai Free の初期化スクリプト。
-- gvenzl/oracle-free は /container-entrypoint-startdb.d 配下のスクリプトを
-- 「起動の度に」 sqlplus -s / as sysdba で実行する。接続先は CDB(FREE) なので、
-- まず PDB(FREEPDB1) へセッションのコンテナを切り替える。
--
-- 目的:
--   1) SCOTT スキーマに Shippers 表（他 DB と同じ 3 行）を作成する。
--   2) 期待する接続文字列 "Data Source=localhost/XE" で接続できるよう、
--      FREEPDB1 に別名サービス XE を追加する（既定のサービス名は FREEPDB1）。
--
-- 毎起動時に実行されるためすべて冪等（既にあれば何もしない）に書いている。
-- また、サービス XE の作成を「最後」に行うことで、
-- 「XE 経由で SCOTT に接続できた＝データ準備完了」とみなせるようにしている
-- （Start-Services.ps1 の準備完了判定 oracle/ready/ready.sql がこれを利用する）。

SET ECHO OFF
SET FEEDBACK OFF
-- PL/SQL ブロック中の空行で文が切れないようにする。
SET SQLBLANKLINES ON

ALTER SESSION SET CONTAINER = FREEPDB1;

-- SCOTT ユーザ。通常は compose の APP_USER/APP_USER_PASSWORD により
-- コンテナ初回起動時に作成済みだが、無い場合はここで作る。
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM dba_users WHERE username = 'SCOTT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER SCOTT IDENTIFIED BY tiger';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO SCOTT';
    EXECUTE IMMEDIATE 'ALTER USER SCOTT QUOTA UNLIMITED ON USERS';
  END IF;
END;
/

-- Shippers 表（他の DB の init スクリプトと同じ内容）。
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n
    FROM dba_tables
   WHERE owner = 'SCOTT' AND table_name = 'SHIPPERS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE SCOTT.Shippers (
        ShipperID   NUMBER        GENERATED BY DEFAULT AS IDENTITY,
        CompanyName VARCHAR2(40)  NOT NULL,
        Phone       VARCHAR2(24)  NOT NULL,
        CONSTRAINT PK_Shippers PRIMARY KEY (ShipperID)
      )]';
    EXECUTE IMMEDIATE q'[INSERT INTO SCOTT.Shippers (CompanyName, Phone) VALUES ('Speedy Express', '(503) 555-9831')]';
    EXECUTE IMMEDIATE q'[INSERT INTO SCOTT.Shippers (CompanyName, Phone) VALUES ('United Package', '(503) 555-3199')]';
    EXECUTE IMMEDIATE q'[INSERT INTO SCOTT.Shippers (CompanyName, Phone) VALUES ('Federal Shipping', '(503) 555-9930')]';
    COMMIT;
  END IF;
END;
/

-- 別名サービス XE。PDB 内で DBMS_SERVICE により作成したサービスは PDB に保存され、
-- 以降は PDB のオープン時に自動起動する（念のため毎回 START_SERVICE も試みる）。
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM dba_services WHERE UPPER(name) = 'XE';
  IF n = 0 THEN
    DBMS_SERVICE.CREATE_SERVICE(service_name => 'XE', network_name => 'XE');
  END IF;
END;
/

BEGIN
  DBMS_SERVICE.START_SERVICE('XE');
EXCEPTION
  -- 既に起動済み（ORA-44305）等は無視する。
  WHEN OTHERS THEN NULL;
END;
/

EXIT
